name: Clang

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install LLVM 17 and Ninja
        run: |
          brew install llvm@17 ninja

      - name: Install Vulkan SDK
        uses: humbletim/install-vulkan-sdk@v1.1.1

      - name: Make local build of libc++ with module enabled
        run: |
          git clone https://github.com/llvm/llvm-project.git
          cd llvm-project
          mkdir build
          CC=$(brew --prefix llvm@17)/bin/clang-17 \
          CXX=$(brew --prefix llvm@17)/bin/clang++ \
          cmake -G Ninja -S runtimes -B build \
            -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi;libunwind"
          ninja -C build
          cd ../

      - name: vcpkg dependencies
        run: |
          git clone https://github.com/microsoft/vcpkg "$HOME/vcpkg"
          $HOME/vcpkg/bootstrap-vcpkg.sh
          $HOME/vcpkg/vcpkg install stb

      - name: Configure
        run: |
          mkdir build
          cmake -S . -B build -G Ninja \
            -DCMAKE_C_COMPILER=$(brew --prefix llvm@17)/bin/clang-17 \
            -DCMAKE_CXX_COMPILER=$(brew --prefix llvm@17)/bin/clang++ \
            -DLIBCXX_BUILD=${{ github.workspace }}/llvm-project/build \
            -DCMAKE_TOOLCHAIN_FILE="$HOME/vcpkg/scripts/buildsystems/vcpkg.cmake"

      - name: Build
        run: |
          ninja -j1 std -C build
          ninja -C build